version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      gha-minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
